spring:
  datasource:
    url: jdbc:mysql://pathventure.cpe8u2qma1fo.eu-north-1.rds.amazonaws.com:3306/seas
    username: tumbwe
    password: tumbwerobert
      #  url: jdbc:mysql://localhost:3306/seas_backend
      #  username: root
      #  password: goma
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mail:
    host: smtp.gmail.com
    port: 465
    username: app.todolis@gmail.com
    password: wltpbbvqpguwmyqh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        starttls:
          enable: true
    protocol: smtp
server:
  port: 8088
