spring:
  datasource:
   url: jdbc:mysql://seas_consistdid:f4246aff84d7a291faa16d65f4495b8ba8b2a716@hpu.h.filess.io:3306/seas_consistdid
   username: seas_consistdid
   password: f4246aff84d7a291faa16d65f4495b8ba8b2a716
#        url: jdbc:mysql://localhost:3306/seas_backend
#        username: root
#        password: goma
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mail:
    host: smtp.gmail.com
    port: 465
    username: app.todolis@gmail.com
    password: wltpbbvqpguwmyqh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        starttls:
          enable: true
    protocol: smtp
server:
  port: 8089
