name: SEAS CICD Flow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}
      - name: Build docker image
        run: docker build -t seas/seas-backend .
      - name: Publish image to docker hub
        rub: docker push seas/seas-backend:latest
  deploy:
    needs: build
    runs-on: [ip-172-31-31-57]
    steps:
        - name: Pull image from docker
          run: docker pull seas/seas-backend:latest
        - name: Delete old container
          run: docker rm -f seas-api-container
        - name:
            run: docker run -d -p 8080:8088 --name seas-api-container seas/seas-backend